events:
  join:
    enabled: true
    message: "&aWelcome to the server, &e%player%!"
    sound:
      enabled: true
      sound: ENTITY_EXPERIENCE_ORB_PICKUP
  quit:
    enabled: true
    message: "&cGoodbye, &e%player%!"
    sound:
      enabled: true
      sound: ENTITY_EXPERIENCE_ORB_PICKUP

messages:
  game-mode:
    changed: "&aYour gamemode has been changed to &e%gamemode%&a."
    modes:
      survival: "Survival"
      creative: "Creative"
      adventure: "Adventure"
      spectator: "Spectator"
  fly:
    enabled: "&aYou have been given the ability to fly."
    disabled: "&cYou have lost the ability to fly."

counter-player: 0